### ISSUE TITLE
Money reward?

### ISSUE THREAD

**Issue by AndroidHackPro** [Awzaw/Parkour#1]
I can't add a command or something like "money: 100" in the last line of end parkour

**Comment by Awzaw** [comment]
Good idea, I'll add that

**Comment by InspectorGadget** [comment]
Hi, the line looks good. Not sure what you're talking about.. Can u explain more?

**Comment by Awzaw** [comment]
I assume he means it should be able to give monetary rewards, not just blocks. I should have time to add that soon

**Comment by InspectorGadget** [comment]
Ok, I'll see if could help you..

**Comment by Tolo0** [comment]
Adding money as a reward is a great idea. maybe you could also add a command option. so we can add like a warp to spawn world after completing the parkour.

**Comment by InspectorGadget** [comment]
Could be done! This isn't hard....

**Comment by Awzaw** [comment]
For the reward line you can now use `1000$`. Only EconomyAPI is supported so far.
