### ISSUE TITLE
Defaut reward only  Parkour 1.5.3 ?

### ISSUE THREAD

**Issue by teracube** [Awzaw/Parkour#10]
PocketMine-MP_1.6.2dev-249_70bd9afd_API-3.0.0-ALPHA6.phar
Plugin Parkour v1.5.3 2017/06/29

Hi,
I can not set other reward that defaut reward with Plugin Parkour v1.5.3
for example if i put on line 4 : 17:5 or wood:5  players get always 64 Diamonds.
Is the synthax correct ?

START sign
Line1: pk
Line2: start
Line3: parkour 01
Line4: 17:5

FINISH sign
Line1: pk
Line2: finish
Line3: parkour 01

Thanks for your help

**Comment by Awzaw** [comment]
This is probably caused by changes to SignChangeEvent in MCPE 1.1. I'll check it, thanks for letting me know.

**Comment by teracube** [comment]
Thanks Awzaw

**Comment by Awzaw** [comment]
Fixed
