### ISSUE TITLE
Player glitched when dead

### ISSUE THREAD

**Issue by omgA4L** [Awzaw/Parkour#6]
After you start a parkour and you fall to your death and die, the player gets glitched and cant respawn, any idea on how to fix this problem?

**Comment by Awzaw** [comment]
I can't reproduce this, are you using the official PocketMine from PMMP? If so, which build?

**Comment by omgA4L** [comment]
No, I was using Genisys at the time. Sorry for the late response

**Comment by Awzaw** [comment]
In that case you'll have to ask Genisys to fix teleporting as Parkour works fine with official PocketMine :-) Seriously though... you probably have another plugin interfering with death events or teleporting - did you try with no other plugins?
