### ISSUE TITLE
feature requests 

### ISSUE THREAD

**Issue by Tolo0** [Awzaw/Parkour#9]
Hi any chance you could add multiple commands to the start sign?
so like for money rewards and so i can make it disable the hud when they start. the BasicHUD plugin clashes with the parkour timer.

**Comment by Awzaw** [comment]
I'll think about adding multiple rewards. As for BasicHUD, you'll have this problem whenever you use two plugins that use popups; for now you could try setting the BasicHUD tick config set to a higher setting instead of the default which is every 10 ticks.

**Comment by Tolo0** [comment]
if commands could be added i was going to add the command to disable the hud when clicking the sign 😊

**Comment by Awzaw** [comment]
Without changing BasicHUD I think the only solution is to give players ```-basichud.user``` permission when they start Parkour, and remove it when they finish. Not pretty, but I'll test.

**Comment by Awzaw** [comment]
Try this: https://poggit.pmmp.io/ci/Awzaw/Parkour/Parkour/Dev:16

To ensure that players don't keep -basichud.user perm if the server stops while playing Parkour this 
means that you can not use the negative -basichud.user permission when basichud-compatibility is enabled in the config

**Comment by Tolo0** [comment]
wow nice work it works perfectly thanks for that 😊
